version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: foodmanager_mysql
    restart: always
    ports:
      - '33306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: foodmanager_db
      MYSQL_USER: foodmanager_user
      MYSQL_PASSWORD: foodmanager_pass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - foodmanager_network

volumes:
  db_data:

networks:
  foodmanager_network:
