version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: foodmanager_mysql
    restart: always
    ports:
      - '33306:3306' # Porta mapeada (Host:Container)
    environment:
      MYSQL_ROOT_PASSWORD: rootpass # Senha do usuário root
      MYSQL_DATABASE: foodmanager_db # Nome do banco de dados
      MYSQL_USER: foodmanager_user # Usuário padrão
      MYSQL_PASSWORD: foodmanager_pass # Senha do usuário padrão
    volumes:
      - db_data:/var/lib/mysql # Volume persistente para dados
    networks:
      - foodmanager_network

volumes:
  db_data:

networks:
  foodmanager_network:
